# Generated by Django 5.0 on 2023-12-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_tag_petition_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
