# Generated by Django 5.0 on 2023-12-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_alter_petition_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
